kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-maintenance-operator
  labels:
    name: node-maintenance-operator
subjects:
- kind: ServiceAccount
  name: node-maintenance-operator
  namespace: node-maintenance-operator
roleRef:
  kind: ClusterRole
  name: node-maintenance-operator
  apiGroup: rbac.authorization.k8s.io
